[workspace]
members = [
  "concepts/smart-pointer",
  "concepts/lists",
  "concepts/macros",
  "concepts/macros/hello_macro",
  "exercises/httpie",
  "exercises/thumbor",
  "exercises/green_threads",
]
