[package]
name = "of32-cong-shang-dao-xia-da-yin-er-cha-shu-ii-lcof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
