[package]
name = "of27-er-cha-shu-de-jing-xiang-lcof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
