[package]
name = "a54-er-cha-sou-suo-shu-de-di-kda-jie-dian-lcof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
