# From: https://github.com/EFanZh/LeetCode/blob/master/.github/workflows/rust.yml
# 一个 Workflow 中的每个 Job 都是单独的机器在跑
name: Rust
on: push
jobs:
  rustfmt:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest

  clippy:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest

  tests:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo test --workspace
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
